{{- if .Values.scaledObject.enabled }}
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: {{ include "nixon-deployable.name" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-deployable.labels" . | nindent 4 }}
spec:
  target:
    service: {{ include "nixon-deployable.name" . }}
    port: {{ .Values.service.ports.http.port }}
  rules:
{{- range .Values.ingress.rules }}
    - hosts:
        - {{ .host }}
      paths:
{{- range .paths }}
        - value: {{ .path }}
{{- end }}
{{- end }}
  scalingMetric:
    concurrency:
      targetValue: 50
{{- end }}