{{- if .Values.scaledObject.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nixon-deployable.proxyServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-deployable.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.scaledObject.interceptorAddress }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      protocol: TCP
      targetPort: proxy
{{- end }}