apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-private
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-argocd-resources.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-vpn-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.service }}
                port:
                  number: 80
