{{ include "nixon-library.networkResource" (dict 
  "name" "argocd-server"
  "namespace" $.Release.Namespace
  "router" $.Values.netbirdNetworkRoute
  "labels" (include "nixon-argocd-resources.labels" $)
) }}