repositories:
  - name: hcloud
    url: https://charts.hetzner.cloud
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: traefik
    url: https://traefik.github.io/charts
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: containeroo
    url: https://charts.containeroo.ch

helmDefaults:
  historyMax: 1
  kubeContext: default

releases:
  - name: nixon-netbird-resources
    namespace: netbird
    chart: ../charts/nixon-netbird-resources
    needs:
      - netbird/netbird-operator
      - external-secrets/external-secrets
    values:
      - ../configuration/base/values.yaml

  - name: nixon-external-secrets-resources
    namespace: external-secrets
    chart: ../charts/nixon-external-secrets-resources
    needs:
      - external-secrets/external-secrets
    values:
      - ../configuration/base/values.yaml

  - name: nixon-monitoring-resources
    namespace: monitoring
    chart: ../charts/nixon-monitoring-resources
    values:
      - ../configuration/base/values.yaml

  - name: nixon-cluster-resources
    namespace: default
    chart: ../charts/nixon-cluster-resources
    values:
      - ../configuration/base/values.yaml

  - name: nixon-argocd-resources
    namespace: argocd
    chart: ../charts/nixon-argocd-resources
    values:
      - ../configuration/base/values.yaml
    needs:
      - argocd/argocd
      - external-secrets/nixon-external-secrets-resources

  - name: nixon-ingress-resources
    namespace: traefik
    chart: ../charts/nixon-ingress-resources
    needs:
      - traefik/traefik

  - name: netbird-operator
    namespace: netbird
    chart: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
    version: 0.8.0
    values:
      - values/netbird-operator.yaml
    needs:
      - cert-manager/cert-manager

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 10.9.0
    values:
      - values/argocd.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.21.0
    values:
      - values/cert-manager.yaml
    needs:
      - monitoring/kube-prometheus-stack

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 41.3.0
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - values/traefik.yaml

  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 2.10.0
    values:
      - values/external-secrets.yaml
    needs:
      - cert-manager/cert-manager

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 88.5.4
    # hooks:
    #   - events: ["prepare"]
    #     showlogs: true
    #     command: "kubectl"
    #     args:
    #       - "label"
    #       - "namespace"
    #       - "monitoring"
    #       - "pod-security.kubernetes.io/enforce=privileged"
    #       - "--overwrite"
    values:
      - values/kube-prometheus-stack.yaml

  - name: loki
    installed: false
    namespace: monitoring
    chart: grafana/loki
    version: 7.3.0
    values:
      - values/loki.yaml

  - name: alloy
    installed: false
    namespace: monitoring
    chart: grafana/alloy
    version: 1.12.0
    values:
      - values/alloy.yaml

  - name: cnpg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    version: 0.29.0
    needs:
      - cert-manager/cert-manager

  - name: cnpg-barman-cloud
    namespace: cnpg-system
    chart: cnpg/plugin-barman-cloud
    version: 0.8.0
    needs:
      - cnpg-system/cnpg
      - cert-manager/cert-manager

  - name: local-path-provisioner
    installed: false
    namespace: kube-system
    chart: containeroo/local-path-provisioner
    version: 0.0.38

  - name: hcloud-ccm
    namespace: kube-system
    chart: hcloud/hcloud-cloud-controller-manager
    version: 1.37.0
    values:
      - values/hcloud-ccm.yaml

  - name: hcloud-csi
    installed: false
    namespace: kube-system
    chart: hcloud/hcloud-csi
    version: 2.22.0

  - name: keda
    installed: false
    namespace: keda
    chart: kedacore/keda
    version: 2.20.2
    needs:
      - cert-manager/cert-manager
      - monitoring/kube-prometheus-stack
    values:
      - values/keda.yaml

  - name: keda-http
    installed: false
    namespace: keda
    chart: kedacore/keda-add-ons-http
    version: 0.15.0
    needs:
      - keda/keda
    values:
      - values/keda-http.yaml
