applicationSets:
  tier9:
    applicationNameTemplate: "{{ .name }}-{{ .environment }}"
    environments:
      - production
    valueFiles:
      - /configuration/base/values.yaml
      - /configuration/tier9/values.yaml
      - /configuration/tier9/{{ .environment }}/{{ .name }}.yaml
    applications:
      - name: tier9-abo-api
      - name: tier9-abo-slime
      - name: tier9-abo-worldchat
      - name: tier9-postgresql
        chart: charts/nixon-cnpg-cluster

  hedgehogscorner:
    applicationNameTemplate: "{{ .name }}-{{ .environment }}"
    environments:
      - production
    valueFiles:
      - /configuration/base/values.yaml
      - /configuration/hedgehogscorner/{{ .environment }}/{{ .name }}.yaml
    applications:
      - name: hedgehogscorner-website

  cluster:
    applicationNameTemplate: "{{ .name }}"
    valueFiles:
      - /configuration/base/values.yaml
      - /configuration/cluster/{{ .name }}.yaml
    applications:
      - name: helm-release-checker
        chart: charts/nixon-cronjob
        namespace: default
