appSetValues:
  - APPSET_NAME: greedymercs-appset
    NAME_TEMPLATE: "{{ .name }}-{{ .environment }}"
    ARGO_FILE_PATH: argocd/workloads/greedymercs-*.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/greedymercs/values.yaml
      - /configuration/greedymercs/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: tier9-appset
    NAME_TEMPLATE: "{{ .name }}-{{ .environment }}"
    ARGO_FILE_PATH: argocd/workloads/tier9-*.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/tier9/values.yaml
      - /configuration/tier9/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: untitledproject-appset
    NAME_TEMPLATE: "{{ .name }}-{{ .environment }}"
    ARGO_FILE_PATH: argocd/workloads/untitledproject-*.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/untitledproject/values.yaml
      - /configuration/untitledproject/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: koruxa-appset
    NAME_TEMPLATE: "{{ .name }}-{{ .environment }}"
    ARGO_FILE_PATH: argocd/workloads/koruxa-*.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/koruxa/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: cluster-appset
    NAME_TEMPLATE: "{{ .name }}"
    ARGO_FILE_PATH: argocd/workloads/cluster.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/cluster/{{ .name }}.yaml

  - APPSET_NAME: hedgehogscorner-appset
    NAME_TEMPLATE: "{{ .name }}-{{ .environment }}"
    ARGO_FILE_PATH: argocd/workloads/hedgehogscorner-*.yaml
    VALUE_FILES:
      - /configuration/base/values.yaml
      - /configuration/hedgehogscorner/{{ .environment }}/{{ .name }}.yaml
