name: HelmReleaseChecker

on:
  push:
    branches:
      - main
    paths:
      - source/helm-release-checker/**
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: joshua-nixon/shared-workflows/.github/workflows/Template.Docker.BuildPush.yaml@v1.12
    with:
      azure-client-id: ${{ vars.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ vars.AZURE_SUB_ID }}
      image-registry: ${{ vars.AZURE_REGISTRY }}
      image-repository: helm-release-checker
      dockerfile-path: ./source/helm-release-checker/Dockerfile
      build-context: ./source/helm-release-checker
    secrets: inherit

  deploy:
    needs:
      - build
    uses: ./.github/workflows/Template.UpdateImage.yaml
    with:
      file-path: configuration/cluster/helm-release-checker.yaml
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
