bootstrap:
  mode: recovery

objectStore:
  enabled: false
  destinationPath: ""

externalObjectStore:
  enabled: false
  destinationPath: ""

databaseRoles: []

storage:
  storageClass: local-path
  size: 10Gi
