replicaCount: 1

extraEnvValues: []

extraVolumes: []

extraVolumeMounts: []

securityContextPreset: restricted

securityContextPresets:
  restricted:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

persistence:
  enabled: false
  claimName: null
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: null

service:
  enabled: false
  ports:
    http:
      enabled: false
      port: 8080
      targetPort: http
      protocol: TCP
    metrics:
      enabled: false
      port: 9182
      targetPort: http
      protocol: TCP

imagePullSecret: null

containerPorts:
  http:
    enabled: false
    containerPort: 8080
  metrics:
    enabled: false
    containerPort: 9182

serviceMonitor:
  enabled: false

dotNetEnvironment: null

hpa:
  enabled: false

readinessProbe:
  enabled: false

ingress:
  enabled: false

scaledObject:
  enabled: false
  interceptorAddress: "keda-add-ons-http-interceptor-proxy.keda"
  scalerAddress: "keda-add-ons-http-external-scaler.keda:9090"
