#cloud-config

# /var/log/cloud-init-output.log

package_reboot_if_required: true

package_update: true

package_upgrade: true

timezone: UTC

locale: en_US.UTF-8

write_files:
  - path: /etc/sysctl.d/99-inotify.conf
    permissions: "0644"
    content: |
      fs.inotify.max_user_instances=8192
      fs.inotify.max_user_watches=524288

runcmd:
  - sysctl --system
  - echo "cloud-init completed"
