{{- $name := printf "%s-rw" (include "nixon-cnpg-cluster.name" .) -}}

{{ include "nixon-library.networkResource" (dict 
  "name" $name 
  "namespace" $.Release.Namespace
  "router" $.Values.netbirdNetworkRoute
  "labels" (include "nixon-cnpg-cluster.labels" $)
) }}