- name: Render agent K3s configuration
  ansible.builtin.template:
    src: agent-config.yaml.j2
    dest: "{{ k3s_config_path }}"
    mode: "0600"

- name: Execute agent K3s install
  ansible.builtin.command: "sh {{ k3s_installer_path }}"
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: "true"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: agent
  register: k3s_install_output
  changed_when: true

- name: Debug agent K3s install output
  ansible.builtin.debug:
    var: k3s_install_output.stdout_lines
